In [48]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import xgboost as xgb # or import lightgbm as lgb
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics

In [49]:
df = pd.read_csv('train.csv', index_col=False)
print("Columns in DataFrame:", df.columns.tolist())
print("DataFrame shape:", df.shape)

Columns in DataFrame: ['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType', 'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather']
DataFrame shape: (77299, 11)

In [50]:
print("Missing values per column:\n", df.isnull().sum())

Missing values per column:
 Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [51]:
if 'Temperature' in df.columns:
    df['Temperature'] = df['Temperature'].fillna(df['Temperature'].median())

# For categorical features
categorical_cols = ['RoadType', 'LargeVehicles', 'Weather', 'Landmarks']
for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')

In [52]:
print("Missing values per column:\n", df.isnull().sum())

Missing values per column:
 Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [53]:
df.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,Unknown,1,Not Allowed,No,16.382587,Unknown
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.382587,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [ ]:
df= df.sort_values(by=['geohash', 'day', 'timestamp']).reset_index(drop=True)

In [54]:
df[['Hour', 'Minute']] = df['timestamp'].str.split(':', expand=True).astype(int)
df['TimeInMinutes'] = df['Hour'] * 60 + df['Minute']
df['sine_time'] = np.sin(2 * np.pi * df['TimeInMinutes'] / 1440)
df['cosine_time'] = np.cos(2 * np.pi * df['TimeInMinutes'] / 1440)

In [ ]:
df['demand_lag_1'] = df.groupby('geohash')['demand'].shift(1)
df['demand_lag_2'] = df.groupby('geohash')['demand'].shift(2)

# Fill the first few empty rows created by the shift
df['demand_lag_1'] = df['demand_lag_1'].fillna(df['demand_lag_1'].median())
df['demand_lag_2'] = df['demand_lag_2'].fillna(df['demand_lag_2'].median())

In [56]:
for col in ['Weather', 'Landmarks']:
    if col in df.columns:
        df[col] = df[col].astype('category').cat.codes

In [57]:
columns_to_encode = ['geohash', 'RoadType', 'LargeVehicles']

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_matrix = encoder.fit_transform(df[columns_to_encode])
encoded_df = pd.DataFrame(encoded_matrix, columns=encoder.get_feature_names_out(columns_to_encode))

# Combine and drop raw categorical columns
df = df.reset_index(drop=True)
df = pd.concat([df, encoded_df], axis=1)
df = df.drop(columns=columns_to_encode)

In [58]:
df.head()

,Index,day,timestamp,demand,NumberofLanes,Landmarks,Temperature,Weather,Hour,Minute,...,geohash_qp0dn5,geohash_qp0dnh,geohash_qp0dnj,geohash_qp0dnn,RoadType_Highway,RoadType_Residential,RoadType_Street,RoadType_Unknown,LargeVehicles_Allowed,LargeVehicles_Not Allowed
0,0,48,0:0,0.048804,1,0,16.382587,4,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,1,48,0:0,0.118507,3,1,31.104565,3,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,2,48,0:0,0.027132,1,0,25.919267,3,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,3,48,0:0,0.003272,1,0,16.382587,1,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,4,48,0:0,0.010819,1,0,10.803667,1,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [59]:
df = df.drop(columns=['Index'], errors='ignore')

In [60]:
df['RoadType_Residential']

0        0.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
77294    1.0
77295    1.0
77296    1.0
77297    1.0
77298    1.0
Name: RoadType_Residential, Length: 77299, dtype: float64

In [61]:
X = df.drop(columns=['demand', 'timestamp', 'Index'], errors='ignore')
y = df['demand']

In [62]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training Features Shape: {X_train.shape}")
print(f"Validation Features Shape: {X_val.shape}\n")

Training Features Shape: (61839, 1265)
Validation Features Shape: (15460, 1265)

In [63]:
model = xgb.XGBRegressor(
    n_estimators=600,
    learning_rate=0.03,
    max_depth=7,
    subsample=0.85, 
    colsample_bytree=0.85,     # Take 85% of columns randomly per tree
    random_state=42,
    n_jobs=-1           # Take 85% of rows randomly per tree to combat overfitting
)
print("Training model...")
model.fit(X,y)

Training model...

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.85, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=600,
             n_jobs=-1, num_parallel_tree=None, ...)

In [64]:
# y_pred = model.predict(X_val)

In [65]:
# # Calculating standard regression metrics
# mae = metrics.mean_absolute_error(y_val, y_pred)
# rmse = np.sqrt(metrics.mean_squared_error(y_val, y_pred))
# r2 = metrics.r2_score(y_val, y_pred)

In [66]:
# competition_score = max(0, 100 * r2)

In [67]:
# print("\n================ EVALUATION METRICS ================")
# print(f"Mean Absolute Error (MAE)        : {mae:.4f}")
# print(f"Root Mean Squared Error (RMSE)   : {rmse:.4f}")
# print(f"Standard R-squared (R²) Score    : {r2:.4f}")
# print(f"CUSTOM COMPETITION ACCURACY SCORE: {competition_score:.4f} / 100")
# print("====================================================")

In [68]:
# # %%
# # Plot 1: Predicted vs. Actual Demand
# plt.figure(figsize=(10, 6))
# sns.scatterplot(x=y_val, y=y_pred, alpha=0.4, color='purple')
# # Perfect prediction line
# plt.plot([y_val.min(), y_val.max()], [y_val.min(), y_val.max()], 'r--', lw=2)
# plt.title('Predicted vs. Actual Demand (Ideal line is Red Dash)')
# plt.xlabel('Actual Demand')
# plt.ylabel('Predicted Demand')
# plt.grid(True)
# plt.show()

In [69]:
# residuals = y_val - y_pred
# plt.figure(figsize=(10, 5))
# sns.histplot(residuals, kde=True, bins=50, color='teal')
# plt.axvline(x=0, color='red', linestyle='--')
# plt.title('Distribution of Prediction Errors (Residuals)')
# plt.xlabel('Error (Actual - Predicted)')
# plt.ylabel('Count')
# plt.show()

In [70]:
df_test = pd.read_csv('test.csv')

if 'Temperature' in df_test.columns:
    df_test['Temperature'] = df_test['Temperature'].fillna(df_test['Temperature'].median())

# For categorical features
categorical_cols = ['RoadType', 'LargeVehicles', 'Weather', 'Landmarks']
for col in categorical_cols:
    if col in df_test.columns:
        df_test[col] = df_test[col].fillna('Unknown')


df_test[['Hour', 'Minute']] = df_test['timestamp'].str.split(':', expand=True).astype(int)
df_test['TimeInMinutes'] = df_test['Hour'] * 60 + df_test['Minute']
df_test['sine_time'] = np.sin(2 * np.pi * df_test['TimeInMinutes'] / 1440)
df_test['cosine_time'] = np.cos(2 * np.pi * df_test['TimeInMinutes'] / 1440)

# df_test['demand_lag_1'] = df_test.groupby('geohash')['demand'].shift(1)
# df_test['demand_lag_2'] = df_test.groupby('geohash')['demand'].shift(2)

# # Fill the first few empty rows created by the shift
# df_test['demand_lag_1'] = df_test['demand_lag_1'].fillna(df_test['demand_lag_1'].median())
# df_test['demand_lag_2'] = df_test['demand_lag_2'].fillna(df_test['demand_lag_2'].median())

for col in ['Weather', 'Landmarks']:
    if col in df_test.columns:
        df_test[col] = df_test[col].astype('category').cat.codes


columns_to_encode = ['geohash', 'RoadType', 'LargeVehicles']

encoder_test = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded_matrix_test = encoder_test.fit_transform(df_test[columns_to_encode])
encoded_df_test = pd.DataFrame(encoded_matrix_test, columns=encoder_test.get_feature_names_out(columns_to_encode))

# Combine and drop raw categorical columns
df_test = df_test.reset_index(drop=True)
df_test = pd.concat([df_test, encoded_df_test], axis=1)
df_test = df_test.drop(columns=columns_to_encode)

X_test_final = df_test.drop(columns=['timestamp', 'Index'], errors='ignore')

In [71]:
test_predictions = model.predict(X_test_final)

# Create submission file
submission = pd.DataFrame({
    'Index': df_test['Index'],
    'demand': test_predictions
})
submission.to_csv('my_submission.csv', index=False)
print("Submission file saved successfully!")

ValueError: feature_names mismatch: ['day', 'NumberofLanes', 'Landmarks', 'Temperature', 'Weather', 'Hour', 'Minute', 'TimeInMinutes', 'sine_time', 'cosine_time', 'geohash_qp02yc', 'geohash_qp02yf', 'geohash_qp02yy', 'geohash_qp02yz', 'geohash_qp02z1', 'geohash_qp02z3', 'geohash_qp02z4', 'geohash_qp02z5', 'geohash_qp02z6', 'geohash_qp02z7', 'geohash_qp02z9', 'geohash_qp02zc', 'geohash_qp02zd', 'geohash_qp02ze', 'geohash_qp02zf', 'geohash_qp02zg', 'geohash_qp02zh', 'geohash_qp02zj', 'geohash_qp02zk', 'geohash_qp02zm', 'geohash_qp02zn', 'geohash_qp02zp', 'geohash_qp02zq', 'geohash_qp02zr', 'geohash_qp02zs', 'geohash_qp02zt', 'geohash_qp02zu', 'geohash_qp02zv', 'geohash_qp02zw', 'geohash_qp02zx', 'geohash_qp02zy', 'geohash_qp02zz', 'geohash_qp03jq', 'geohash_qp03jr', 'geohash_qp03jw', 'geohash_qp03jx', 'geohash_qp03jy', 'geohash_qp03jz', 'geohash_qp03m2', 'geohash_qp03m3', 'geohash_qp03m6', 'geohash_qp03m7', 'geohash_qp03m8', 'geohash_qp03m9', 'geohash_qp03mb', 'geohash_qp03mc', 'geohash_qp03md', 'geohash_qp03me', 'geohash_qp03mf', 'geohash_qp03mg', 'geohash_qp03mk', 'geohash_qp03mm', 'geohash_qp03mq', 'geohash_qp03mr', 'geohash_qp03ms', 'geohash_qp03mt', 'geohash_qp03mu', 'geohash_qp03mv', 'geohash_qp03mw', 'geohash_qp03mx', 'geohash_qp03my', 'geohash_qp03mz', 'geohash_qp03nb', 'geohash_qp03nd', 'geohash_qp03nf', 'geohash_qp03nn', 'geohash_qp03np', 'geohash_qp03nq', 'geohash_qp03nr', 'geohash_qp03nw', 'geohash_qp03nx', 'geohash_qp03ny', 'geohash_qp03nz', 'geohash_qp03p0', 'geohash_qp03p1', 'geohash_qp03p2', 'geohash_qp03p3', 'geohash_qp03p4', 'geohash_qp03p5', 'geohash_qp03p6', 'geohash_qp03p7', 'geohash_qp03p8', 'geohash_qp03p9', 'geohash_qp03pb', 'geohash_qp03pc', 'geohash_qp03pd', 'geohash_qp03pe', 'geohash_qp03pf', 'geohash_qp03pg', 'geohash_qp03pk', 'geohash_qp03pm', 'geohash_qp03pn', 'geohash_qp03pp', 'geohash_qp03pq', 'geohash_qp03pr', 'geohash_qp03ps', 'geohash_qp03pt', 'geohash_qp03pu', 'geohash_qp03pv', 'geohash_qp03pw', 'geohash_qp03px', 'geohash_qp03py', 'geohash_qp03pz', 'geohash_qp03q0', 'geohash_qp03q1', 'geohash_qp03q2', 'geohash_qp03q3', 'geohash_qp03q4', 'geohash_qp03q5', 'geohash_qp03q6', 'geohash_qp03q7', 'geohash_qp03q8', 'geohash_qp03q9', 'geohash_qp03qb', 'geohash_qp03qc', 'geohash_qp03qd', 'geohash_qp03qe', 'geohash_qp03qf', 'geohash_qp03qg', 'geohash_qp03qh', 'geohash_qp03qj', 'geohash_qp03qk', 'geohash_qp03qm', 'geohash_qp03qn', 'geohash_qp03qp', 'geohash_qp03qq', 'geohash_qp03qr', 'geohash_qp03qs', 'geohash_qp03qt', 'geohash_qp03qu', 'geohash_qp03qv', 'geohash_qp03qw', 'geohash_qp03qx', 'geohash_qp03qy', 'geohash_qp03qz', 'geohash_qp03r0', 'geohash_qp03r1', 'geohash_qp03r2', 'geohash_qp03r3', 'geohash_qp03r4', 'geohash_qp03r5', 'geohash_qp03r6', 'geohash_qp03r7', 'geohash_qp03r8', 'geohash_qp03r9', 'geohash_qp03rb', 'geohash_qp03rc', 'geohash_qp03rd', 'geohash_qp03re', 'geohash_qp03rf', 'geohash_qp03rg', 'geohash_qp03rh', 'geohash_qp03rj', 'geohash_qp03rk', 'geohash_qp03rm', 'geohash_qp03rn', 'geohash_qp03rp', 'geohash_qp03rq', 'geohash_qp03rr', 'geohash_qp03rs', 'geohash_qp03rt', 'geohash_qp03ru', 'geohash_qp03rv', 'geohash_qp03rw', 'geohash_qp03rx', 'geohash_qp03ry', 'geohash_qp03rz', 'geohash_qp03t2', 'geohash_qp03t3', 'geohash_qp03t6', 'geohash_qp03t7', 'geohash_qp03t8', 'geohash_qp03t9', 'geohash_qp03tb', 'geohash_qp03tc', 'geohash_qp03td', 'geohash_qp03te', 'geohash_qp03tf', 'geohash_qp03tg', 'geohash_qp03tk', 'geohash_qp03tm', 'geohash_qp03tq', 'geohash_qp03tr', 'geohash_qp03ts', 'geohash_qp03tt', 'geohash_qp03tu', 'geohash_qp03tv', 'geohash_qp03tw', 'geohash_qp03tx', 'geohash_qp03ty', 'geohash_qp03tz', 'geohash_qp03v2', 'geohash_qp03v9', 'geohash_qp03vb', 'geohash_qp03vc', 'geohash_qp03vd', 'geohash_qp03w0', 'geohash_qp03w1', 'geohash_qp03w2', 'geohash_qp03w3', 'geohash_qp03w4', 'geohash_qp03w5', 'geohash_qp03w6', 'geohash_qp03w7', 'geohash_qp03w8', 'geohash_qp03w9', 'geohash_qp03wb', 'geohash_qp03wc', 'geohash_qp03wd', 'geohash_qp03we', 'geohash_qp03wf', 'geohash_qp03wg', 'geohash_qp03wh', 'geohash_qp03wj', 'geohash_qp03wk', 'geohash_qp03wm', 'geohash_qp03wn', 'geohash_qp03wp', 'geohash_qp03wq', 'geohash_qp03wr', 'geohash_qp03ws', 'geohash_qp03wt', 'geohash_qp03wu', 'geohash_qp03wv', 'geohash_qp03ww', 'geohash_qp03wx', 'geohash_qp03wy', 'geohash_qp03wz', 'geohash_qp03x0', 'geohash_qp03x1', 'geohash_qp03x2', 'geohash_qp03x3', 'geohash_qp03x4', 'geohash_qp03x5', 'geohash_qp03x6', 'geohash_qp03x7', 'geohash_qp03x8', 'geohash_qp03x9', 'geohash_qp03xb', 'geohash_qp03xc', 'geohash_qp03xd', 'geohash_qp03xe', 'geohash_qp03xf', 'geohash_qp03xg', 'geohash_qp03xh', 'geohash_qp03xj', 'geohash_qp03xk', 'geohash_qp03xm', 'geohash_qp03xn', 'geohash_qp03xp', 'geohash_qp03xq', 'geohash_qp03xr', 'geohash_qp03xs', 'geohash_qp03xt', 'geohash_qp03xu', 'geohash_qp03xv', 'geohash_qp03xw', 'geohash_qp03xx', 'geohash_qp03xy', 'geohash_qp03xz', 'geohash_qp03y0', 'geohash_qp03y1', 'geohash_qp03y2', 'geohash_qp03y3', 'geohash_qp03y4', 'geohash_qp03y5', 'geohash_qp03y6', 'geohash_qp03y7', 'geohash_qp03y8', 'geohash_qp03y9', 'geohash_qp03yb', 'geohash_qp03yc', 'geohash_qp03yd', 'geohash_qp03ye', 'geohash_qp03yf', 'geohash_qp03yg', 'geohash_qp03yk', 'geohash_qp03ym', 'geohash_qp03yn', 'geohash_qp03yq', 'geohash_qp03yr', 'geohash_qp03ys', 'geohash_qp03yt', 'geohash_qp03yu', 'geohash_qp03yv', 'geohash_qp03yw', 'geohash_qp03yx', 'geohash_qp03yy', 'geohash_qp03yz', 'geohash_qp03z0', 'geohash_qp03z1', 'geohash_qp03z2', 'geohash_qp03z3', 'geohash_qp03z4', 'geohash_qp03z5', 'geohash_qp03z6', 'geohash_qp03z7', 'geohash_qp03z8', 'geohash_qp03z9', 'geohash_qp03zb', 'geohash_qp03zc', 'geohash_qp03zd', 'geohash_qp03ze', 'geohash_qp03zf', 'geohash_qp03zg', 'geohash_qp03zh', 'geohash_qp03zj', 'geohash_qp03zk', 'geohash_qp03zm', 'geohash_qp03zn', 'geohash_qp03zp', 'geohash_qp03zq', 'geohash_qp03zr', 'geohash_qp03zs', 'geohash_qp03zt', 'geohash_qp03zu', 'geohash_qp03zv', 'geohash_qp03zw', 'geohash_qp03zy', 'geohash_qp03zz', 'geohash_qp06n8', 'geohash_qp06n9', 'geohash_qp06nb', 'geohash_qp06nc', 'geohash_qp06nd', 'geohash_qp06ne', 'geohash_qp06nf', 'geohash_qp06ng', 'geohash_qp06ns', 'geohash_qp06nt', 'geohash_qp06nu', 'geohash_qp06nv', 'geohash_qp06ny', 'geohash_qp06p0', 'geohash_qp06p1', 'geohash_qp06p2', 'geohash_qp06p3', 'geohash_qp06p4', 'geohash_qp06p5', 'geohash_qp06p6', 'geohash_qp06p7', 'geohash_qp06p8', 'geohash_qp06p9', 'geohash_qp06pb', 'geohash_qp06pc', 'geohash_qp06pd', 'geohash_qp06pe', 'geohash_qp06pf', 'geohash_qp06pg', 'geohash_qp06ph', 'geohash_qp06pj', 'geohash_qp06pk', 'geohash_qp06pm', 'geohash_qp06pn', 'geohash_qp06pq', 'geohash_qp06ps', 'geohash_qp06pt', 'geohash_qp06pu', 'geohash_qp06pv', 'geohash_qp06pw', 'geohash_qp06py', 'geohash_qp08b1', 'geohash_qp08b4', 'geohash_qp08b5', 'geohash_qp08b6', 'geohash_qp08b7', 'geohash_qp08bd', 'geohash_qp08be', 'geohash_qp08bg', 'geohash_qp08bh', 'geohash_qp08bj', 'geohash_qp08bk', 'geohash_qp08bm', 'geohash_qp08bn', 'geohash_qp08bp', 'geohash_qp08bq', 'geohash_qp08br', 'geohash_qp08bs', 'geohash_qp08bt', 'geohash_qp08bu', 'geohash_qp08bv', 'geohash_qp08bw', 'geohash_qp08bx', 'geohash_qp08by', 'geohash_qp08bz', 'geohash_qp08c5', 'geohash_qp08cj', 'geohash_qp08ck', 'geohash_qp08cm', 'geohash_qp08cn', 'geohash_qp08cp', 'geohash_qp08cv', 'geohash_qp08cy', 'geohash_qp08fh', 'geohash_qp08fj', 'geohash_qp08fn', 'geohash_qp08fp', 'geohash_qp08fq', 'geohash_qp08fr', 'geohash_qp08fv', 'geohash_qp08fw', 'geohash_qp08fx', 'geohash_qp08fy', 'geohash_qp08fz', 'geohash_qp08g5', 'geohash_qp08g6', 'geohash_qp08g7', 'geohash_qp08gh', 'geohash_qp08gj', 'geohash_qp08gk', 'geohash_qp08gm', 'geohash_qp08gn', 'geohash_qp08gp', 'geohash_qp08gq', 'geohash_qp08gr', 'geohash_qp08gs', 'geohash_qp08gt', 'geohash_qp08gu', 'geohash_qp08gv', 'geohash_qp08gw', 'geohash_qp08gx', 'geohash_qp08gy', 'geohash_qp08gz', 'geohash_qp08uj', 'geohash_qp08un', 'geohash_qp08up', 'geohash_qp0900', 'geohash_qp0901', 'geohash_qp0902', 'geohash_qp0903', 'geohash_qp0904', 'geohash_qp0905', 'geohash_qp0906', 'geohash_qp0907', 'geohash_qp0908', 'geohash_qp0909', 'geohash_qp090b', 'geohash_qp090c', 'geohash_qp090d', 'geohash_qp090e', 'geohash_qp090h', 'geohash_qp090j', 'geohash_qp090k', 'geohash_qp090m', 'geohash_qp090n', 'geohash_qp090p', 'geohash_qp090q', 'geohash_qp090r', 'geohash_qp090s', 'geohash_qp090t', 'geohash_qp090v', 'geohash_qp090w', 'geohash_qp090x', 'geohash_qp090y', 'geohash_qp090z', 'geohash_qp0917', 'geohash_qp091e', 'geohash_qp091g', 'geohash_qp091k', 'geohash_qp091m', 'geohash_qp091q', 'geohash_qp091r', 'geohash_qp091s', 'geohash_qp091t', 'geohash_qp091u', 'geohash_qp091v', 'geohash_qp091w', 'geohash_qp091x', 'geohash_qp091y', 'geohash_qp091z', 'geohash_qp0920', 'geohash_qp0921', 'geohash_qp0922', 'geohash_qp0923', 'geohash_qp0924', 'geohash_qp0925', 'geohash_qp0926', 'geohash_qp0927', 'geohash_qp0928', 'geohash_qp0929', 'geohash_qp092d', 'geohash_qp092e', 'geohash_qp092h', 'geohash_qp092j', 'geohash_qp092k', 'geohash_qp092m', 'geohash_qp092n', 'geohash_qp092p', 'geohash_qp092q', 'geohash_qp092r', 'geohash_qp092s', 'geohash_qp092t', 'geohash_qp092w', 'geohash_qp092x', 'geohash_qp092z', 'geohash_qp0930', 'geohash_qp0931', 'geohash_qp0932', 'geohash_qp0933', 'geohash_qp0934', 'geohash_qp0936', 'geohash_qp0937', 'geohash_qp0938', 'geohash_qp093b', 'geohash_qp093c', 'geohash_qp093d', 'geohash_qp093e', 'geohash_qp093f', 'geohash_qp093g', 'geohash_qp093h', 'geohash_qp093j', 'geohash_qp093k', 'geohash_qp093m', 'geohash_qp093n', 'geohash_qp093p', 'geohash_qp093q', 'geohash_qp093r', 'geohash_qp093s', 'geohash_qp093t', 'geohash_qp093u', 'geohash_qp093v', 'geohash_qp093w', 'geohash_qp093x', 'geohash_qp093y', 'geohash_qp093z', 'geohash_qp0941', 'geohash_qp0942', 'geohash_qp0943', 'geohash_qp0944', 'geohash_qp0945', 'geohash_qp0946', 'geohash_qp0947', 'geohash_qp0948', 'geohash_qp0949', 'geohash_qp094b', 'geohash_qp094c', 'geohash_qp094d', 'geohash_qp094e', 'geohash_qp094f', 'geohash_qp094g', 'geohash_qp094h', 'geohash_qp094j', 'geohash_qp094k', 'geohash_qp094m', 'geohash_qp094n', 'geohash_qp094p', 'geohash_qp094q', 'geohash_qp094r', 'geohash_qp094s', 'geohash_qp094t', 'geohash_qp094u', 'geohash_qp094v', 'geohash_qp094w', 'geohash_qp094x', 'geohash_qp094y', 'geohash_qp094z', 'geohash_qp0950', 'geohash_qp0951', 'geohash_qp0952', 'geohash_qp0953', 'geohash_qp0954', 'geohash_qp0956', 'geohash_qp0957', 'geohash_qp0958', 'geohash_qp0959', 'geohash_qp095b', 'geohash_qp095c', 'geohash_qp095d', 'geohash_qp095e', 'geohash_qp095f', 'geohash_qp095g', 'geohash_qp095h', 'geohash_qp095j', 'geohash_qp095k', 'geohash_qp095m', 'geohash_qp095n', 'geohash_qp095p', 'geohash_qp095q', 'geohash_qp095r', 'geohash_qp095s', 'geohash_qp095t', 'geohash_qp095u', 'geohash_qp095v', 'geohash_qp095w', 'geohash_qp095x', 'geohash_qp095y', 'geohash_qp095z', 'geohash_qp0960', 'geohash_qp0961', 'geohash_qp0962', 'geohash_qp0963', 'geohash_qp0968', 'geohash_qp0969', 'geohash_qp096b', 'geohash_qp096c', 'geohash_qp096d', 'geohash_qp096e', 'geohash_qp096f', 'geohash_qp096g', 'geohash_qp096h', 'geohash_qp096j', 'geohash_qp096k', 'geohash_qp096m', 'geohash_qp096n', 'geohash_qp096p', 'geohash_qp096q', 'geohash_qp096r', 'geohash_qp096s', 'geohash_qp096t', 'geohash_qp096u', 'geohash_qp096v', 'geohash_qp096w', 'geohash_qp096x', 'geohash_qp096y', 'geohash_qp096z', 'geohash_qp0970', 'geohash_qp0971', 'geohash_qp0972', 'geohash_qp0973', 'geohash_qp0974', 'geohash_qp0975', 'geohash_qp0976', 'geohash_qp0977', 'geohash_qp0978', 'geohash_qp0979', 'geohash_qp097b', 'geohash_qp097c', 'geohash_qp097d', 'geohash_qp097e', 'geohash_qp097f', 'geohash_qp097g', 'geohash_qp097h', 'geohash_qp097j', 'geohash_qp097k', 'geohash_qp097m', 'geohash_qp097n', 'geohash_qp097p', 'geohash_qp097q', 'geohash_qp097r', 'geohash_qp097s', 'geohash_qp097t', 'geohash_qp097u', 'geohash_qp097v', 'geohash_qp097w', 'geohash_qp097x', 'geohash_qp097y', 'geohash_qp097z', 'geohash_qp0980', 'geohash_qp0981', 'geohash_qp0982', 'geohash_qp0983', 'geohash_qp0984', 'geohash_qp0985', 'geohash_qp0986', 'geohash_qp0987', 'geohash_qp0988', 'geohash_qp0989', 'geohash_qp098b', 'geohash_qp098c', 'geohash_qp098d', 'geohash_qp098e', 'geohash_qp098f', 'geohash_qp098g', 'geohash_qp098h', 'geohash_qp098j', 'geohash_qp098k', 'geohash_qp098m', 'geohash_qp098n', 'geohash_qp098p', 'geohash_qp098q', 'geohash_qp098r', 'geohash_qp098u', 'geohash_qp098v', 'geohash_qp0990', 'geohash_qp0991', 'geohash_qp0992', 'geohash_qp0993', 'geohash_qp0994', 'geohash_qp0995', 'geohash_qp0996', 'geohash_qp0997', 'geohash_qp0998', 'geohash_qp0999', 'geohash_qp099b', 'geohash_qp099c', 'geohash_qp099d', 'geohash_qp099e', 'geohash_qp099f', 'geohash_qp099g', 'geohash_qp099h', 'geohash_qp099j', 'geohash_qp099k', 'geohash_qp099m', 'geohash_qp099n', 'geohash_qp099p', 'geohash_qp099q', 'geohash_qp099r', 'geohash_qp099s', 'geohash_qp099t', 'geohash_qp099u', 'geohash_qp099v', 'geohash_qp099w', 'geohash_qp099x', 'geohash_qp099y', 'geohash_qp099z', 'geohash_qp09b0', 'geohash_qp09b1', 'geohash_qp09b2', 'geohash_qp09b3', 'geohash_qp09b4', 'geohash_qp09b5', 'geohash_qp09b6', 'geohash_qp09b7', 'geohash_qp09bd', 'geohash_qp09be', 'geohash_qp09bh', 'geohash_qp09bj', 'geohash_qp09bk', 'geohash_qp09bm', 'geohash_qp09bn', 'geohash_qp09bp', 'geohash_qp09bq', 'geohash_qp09br', 'geohash_qp09bt', 'geohash_qp09bv', 'geohash_qp09bw', 'geohash_qp09bx', 'geohash_qp09bz', 'geohash_qp09c2', 'geohash_qp09c6', 'geohash_qp09c7', 'geohash_qp09c8', 'geohash_qp09c9', 'geohash_qp09cb', 'geohash_qp09cc', 'geohash_qp09cd', 'geohash_qp09ce', 'geohash_qp09cf', 'geohash_qp09cg', 'geohash_qp09ch', 'geohash_qp09cj', 'geohash_qp09ck', 'geohash_qp09cm', 'geohash_qp09cn', 'geohash_qp09cp', 'geohash_qp09cq', 'geohash_qp09cr', 'geohash_qp09cs', 'geohash_qp09ct', 'geohash_qp09cu', 'geohash_qp09cv', 'geohash_qp09cw', 'geohash_qp09cx', 'geohash_qp09cy', 'geohash_qp09cz', 'geohash_qp09d1', 'geohash_qp09d2', 'geohash_qp09d3', 'geohash_qp09d4', 'geohash_qp09d5', 'geohash_qp09d6', 'geohash_qp09d7', 'geohash_qp09d8', 'geohash_qp09d9', 'geohash_qp09db', 'geohash_qp09dc', 'geohash_qp09dd', 'geohash_qp09de', 'geohash_qp09df', 'geohash_qp09dg', 'geohash_qp09dh', 'geohash_qp09dj', 'geohash_qp09dk', 'geohash_qp09dm', 'geohash_qp09dn', 'geohash_qp09dp', 'geohash_qp09dq', 'geohash_qp09dr', 'geohash_qp09ds', 'geohash_qp09dt', 'geohash_qp09du', 'geohash_qp09dv', 'geohash_qp09dw', 'geohash_qp09dx', 'geohash_qp09e0', 'geohash_qp09e1', 'geohash_qp09e2', 'geohash_qp09e3', 'geohash_qp09e4', 'geohash_qp09e5', 'geohash_qp09e6', 'geohash_qp09e7', 'geohash_qp09e8', 'geohash_qp09e9', 'geohash_qp09eb', 'geohash_qp09ec', 'geohash_qp09ed', 'geohash_qp09ee', 'geohash_qp09ef', 'geohash_qp09eh', 'geohash_qp09ej', 'geohash_qp09ek', 'geohash_qp09em', 'geohash_qp09en', 'geohash_qp09ep', 'geohash_qp09eq', 'geohash_qp09er', 'geohash_qp09es', 'geohash_qp09et', 'geohash_qp09eu', 'geohash_qp09ev', 'geohash_qp09ew', 'geohash_qp09ex', 'geohash_qp09ey', 'geohash_qp09ez', 'geohash_qp09f0', 'geohash_qp09f1', 'geohash_qp09f2', 'geohash_qp09f3', 'geohash_qp09f4', 'geohash_qp09f5', 'geohash_qp09f6', 'geohash_qp09f7', 'geohash_qp09f8', 'geohash_qp09f9', 'geohash_qp09fb', 'geohash_qp09fc', 'geohash_qp09fd', 'geohash_qp09fe', 'geohash_qp09ff', 'geohash_qp09fg', 'geohash_qp09fh', 'geohash_qp09fj', 'geohash_qp09fk', 'geohash_qp09fm', 'geohash_qp09fq', 'geohash_qp09fr', 'geohash_qp09fs', 'geohash_qp09ft', 'geohash_qp09fu', 'geohash_qp09fv', 'geohash_qp09fw', 'geohash_qp09fx', 'geohash_qp09fy', 'geohash_qp09fz', 'geohash_qp09g0', 'geohash_qp09g1', 'geohash_qp09g2', 'geohash_qp09g3', 'geohash_qp09g4', 'geohash_qp09g5', 'geohash_qp09g6', 'geohash_qp09g7', 'geohash_qp09g8', 'geohash_qp09g9', 'geohash_qp09gb', 'geohash_qp09gc', 'geohash_qp09gd', 'geohash_qp09ge', 'geohash_qp09gf', 'geohash_qp09gg', 'geohash_qp09gh', 'geohash_qp09gj', 'geohash_qp09gk', 'geohash_qp09gm', 'geohash_qp09gn', 'geohash_qp09gp', 'geohash_qp09gq', 'geohash_qp09gr', 'geohash_qp09gs', 'geohash_qp09gt', 'geohash_qp09gu', 'geohash_qp09gv', 'geohash_qp09gw', 'geohash_qp09gx', 'geohash_qp09gy', 'geohash_qp09gz', 'geohash_qp09h0', 'geohash_qp09h1', 'geohash_qp09h4', 'geohash_qp09h5', 'geohash_qp09h6', 'geohash_qp09h7', 'geohash_qp09he', 'geohash_qp09hh', 'geohash_qp09hj', 'geohash_qp09hk', 'geohash_qp09hm', 'geohash_qp09hn', 'geohash_qp09hp', 'geohash_qp09hq', 'geohash_qp09hr', 'geohash_qp09hs', 'geohash_qp09ht', 'geohash_qp09hv', 'geohash_qp09hw', 'geohash_qp09hx', 'geohash_qp09hy', 'geohash_qp09hz', 'geohash_qp09j7', 'geohash_qp09jb', 'geohash_qp09jc', 'geohash_qp09jd', 'geohash_qp09je', 'geohash_qp09jf', 'geohash_qp09jg', 'geohash_qp09jj', 'geohash_qp09jk', 'geohash_qp09jm', 'geohash_qp09jn', 'geohash_qp09jp', 'geohash_qp09jq', 'geohash_qp09jr', 'geohash_qp09js', 'geohash_qp09jt', 'geohash_qp09ju', 'geohash_qp09jv', 'geohash_qp09jx', 'geohash_qp09jz', 'geohash_qp09k0', 'geohash_qp09k1', 'geohash_qp09k2', 'geohash_qp09k3', 'geohash_qp09k4', 'geohash_qp09k5', 'geohash_qp09k6', 'geohash_qp09k7', 'geohash_qp09k8', 'geohash_qp09k9', 'geohash_qp09kb', 'geohash_qp09kc', 'geohash_qp09kd', 'geohash_qp09ke', 'geohash_qp09kf', 'geohash_qp09kj', 'geohash_qp09km', 'geohash_qp09kn', 'geohash_qp09kq', 'geohash_qp09kr', 'geohash_qp09ks', 'geohash_qp09kt', 'geohash_qp09ku', 'geohash_qp09kv', 'geohash_qp09kw', 'geohash_qp09kx', 'geohash_qp09ky', 'geohash_qp09kz', 'geohash_qp09m0', 'geohash_qp09m1', 'geohash_qp09m2', 'geohash_qp09m3', 'geohash_qp09m7', 'geohash_qp09m8', 'geohash_qp09m9', 'geohash_qp09mb', 'geohash_qp09mc', 'geohash_qp09md', 'geohash_qp09me', 'geohash_qp09mj', 'geohash_qp09mm', 'geohash_qp09mn', 'geohash_qp09mp', 'geohash_qp09mq', 'geohash_qp09mr', 'geohash_qp09ms', 'geohash_qp09mt', 'geohash_qp09mu', 'geohash_qp09mw', 'geohash_qp09mx', 'geohash_qp09mz', 'geohash_qp09n4', 'geohash_qp09np', 'geohash_qp09q0', 'geohash_qp09q1', 'geohash_qp09q4', 'geohash_qp09q5', 'geohash_qp09qj', 'geohash_qp09qn', 'geohash_qp09qp', 'geohash_qp09s1', 'geohash_qp09s2', 'geohash_qp09s3', 'geohash_qp09s4', 'geohash_qp09s6', 'geohash_qp09s7', 'geohash_qp09s8', 'geohash_qp09s9', 'geohash_qp09sb', 'geohash_qp09sc', 'geohash_qp09sd', 'geohash_qp09se', 'geohash_qp09sf', 'geohash_qp09sg', 'geohash_qp09sh', 'geohash_qp09sj', 'geohash_qp09sk', 'geohash_qp09sm', 'geohash_qp09sn', 'geohash_qp09sp', 'geohash_qp09sq', 'geohash_qp09sr', 'geohash_qp09ss', 'geohash_qp09st', 'geohash_qp09su', 'geohash_qp09sv', 'geohash_qp09sw', 'geohash_qp09sx', 'geohash_qp09sy', 'geohash_qp09sz', 'geohash_qp09t0', 'geohash_qp09t1', 'geohash_qp09t2', 'geohash_qp09t4', 'geohash_qp09t5', 'geohash_qp09t8', 'geohash_qp09t9', 'geohash_qp09th', 'geohash_qp09tj', 'geohash_qp09tk', 'geohash_qp09tm', 'geohash_qp09tn', 'geohash_qp09tp', 'geohash_qp09tq', 'geohash_qp09tr', 'geohash_qp09ts', 'geohash_qp09tt', 'geohash_qp09tw', 'geohash_qp09tx', 'geohash_qp09u0', 'geohash_qp09u1', 'geohash_qp09u2', 'geohash_qp09u3', 'geohash_qp09u4', 'geohash_qp09u5', 'geohash_qp09u6', 'geohash_qp09u7', 'geohash_qp09u8', 'geohash_qp09u9', 'geohash_qp09ub', 'geohash_qp09uc', 'geohash_qp09ud', 'geohash_qp09ue', 'geohash_qp09uf', 'geohash_qp09ug', 'geohash_qp09uh', 'geohash_qp09uj', 'geohash_qp09uk', 'geohash_qp09um', 'geohash_qp09un', 'geohash_qp09up', 'geohash_qp09uq', 'geohash_qp09ur', 'geohash_qp09us', 'geohash_qp09ut', 'geohash_qp09uu', 'geohash_qp09uv', 'geohash_qp09uw', 'geohash_qp09ux', 'geohash_qp09uy', 'geohash_qp09uz', 'geohash_qp09v0', 'geohash_qp09v1', 'geohash_qp09v2', 'geohash_qp09v3', 'geohash_qp09v4', 'geohash_qp09v6', 'geohash_qp09v7', 'geohash_qp09v8', 'geohash_qp09vc', 'geohash_qp09vd', 'geohash_qp09ve', 'geohash_qp09vf', 'geohash_qp09vg', 'geohash_qp09vj', 'geohash_qp09vk', 'geohash_qp09vm', 'geohash_qp09vn', 'geohash_qp09vp', 'geohash_qp09vq', 'geohash_qp09vr', 'geohash_qp09vs', 'geohash_qp09vt', 'geohash_qp09vu', 'geohash_qp09vv', 'geohash_qp09vw', 'geohash_qp09vx', 'geohash_qp09vy', 'geohash_qp09vz', 'geohash_qp09w0', 'geohash_qp09w4', 'geohash_qp09w5', 'geohash_qp09wp', 'geohash_qp09y1', 'geohash_qp09y4', 'geohash_qp09y5', 'geohash_qp09yh', 'geohash_qp09yj', 'geohash_qp09yn', 'geohash_qp09yp', 'geohash_qp0d00', 'geohash_qp0d01', 'geohash_qp0d02', '